// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWzEACa8qXHZwis_4EBsMPyGXf3QzhVA',
    appId: '1:935726813994:web:7a702eb0b8418f48abc453',
    messagingSenderId: '935726813994',
    projectId: 'smartaiapp-3660c',
    authDomain: 'smartaiapp-3660c.firebaseapp.com',
    storageBucket: 'smartaiapp-3660c.firebasestorage.app',
    measurementId: 'G-T672SX7J8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_BHD6bQd3dAzAhIwN3wmrjjBNHwEjlM',
    appId: '1:935726813994:android:385250d3e2ba2a5babc453',
    messagingSenderId: '935726813994',
    projectId: 'smartaiapp-3660c',
    storageBucket: 'smartaiapp-3660c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKhtv7Wr25WVpaeqFaemBRERPbW8-AzY',
    appId: '1:935726813994:ios:ff62251985cf7ee4abc453',
    messagingSenderId: '935726813994',
    projectId: 'smartaiapp-3660c',
    storageBucket: 'smartaiapp-3660c.firebasestorage.app',
    iosClientId: '935726813994-sqcl90v0i6tpa55okh8594u8hn1qu0hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKhtv7Wr25WVpaeqFaemBRERPbW8-AzY',
    appId: '1:935726813994:ios:ff62251985cf7ee4abc453',
    messagingSenderId: '935726813994',
    projectId: 'smartaiapp-3660c',
    storageBucket: 'smartaiapp-3660c.firebasestorage.app',
    iosClientId: '935726813994-sqcl90v0i6tpa55okh8594u8hn1qu0hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWzEACa8qXHZwis_4EBsMPyGXf3QzhVA',
    appId: '1:935726813994:web:9831721e6d524898abc453',
    messagingSenderId: '935726813994',
    projectId: 'smartaiapp-3660c',
    authDomain: 'smartaiapp-3660c.firebaseapp.com',
    storageBucket: 'smartaiapp-3660c.firebasestorage.app',
    measurementId: 'G-L02VPRXDXK',
  );
}
